- name: MySQLをインストールする
  apt:
    name:  mysql-server
    state: present

- name: Ansibleのmysql_dbモジュールを使うために必要なパッケージをインストールする
  apt:
    name:  python-mysqldb
    state: present

- name: MySQLの設定ファイルを更新する
  template:
    src:  my.cnf
    dest: /etc/mysql/my.cnf

- name: ib_logfilesを削除する
  shell: rm -rf /var/lib/mysql/ib_logfile*

- name: MySQLを再起動する
  service:
    name:  mysql
    state: restarted

- name: rootユーザを作成する
  mysql_user:
    user:     '{{ mysql_root_user_name }}'
    password: '{{ mysql_root_user_password }}'
    host:     '%'
    priv:     '*.*:ALL,GRANT'

- name: /root/.my.cnf を作成する
  template:
    src:  .my.cnf
    dest: /root/.my.cnf

- name: 既存のrootユーザを削除する (IPv6 localhost (::1))
  mysql_user:
    user:  root
    host:  '::1'
    state: absent

- name: 既存のrootユーザを削除する (IPv4 localhost (127.0.0.1))
  mysql_user:
    user:  root
    host:  127.0.0.1
    state: absent

- name: 既存のrootユーザを削除する (localhost)
  mysql_user:
    user:  root
    host:  localhost
    state: absent

- name: 既存のrootユーザを削除する (サーバのホスト名)
  mysql_user:
    user:  root
    host:  '{{ ansible_hostname }}'
    state: absent

- name: データベースを作成する
  mysql_db:
    db:    '{{ mysql_db_name }}'
    state: present

- name: データベースユーザを作成する
  mysql_user:
    name:     '{{ mysql_user_name }}'
    password: '{{ mysql_user_password }}'
    host:     '%'
    priv:     '{{ mysql_db_name }}.*:ALL,GRANT'
    state:    present
